### ISSUE TITLE
Fails to build with VS2012? (or 13?)

### ISSUE THREAD

**Issue by voltagex** [atom/node-pathwatcher#21]
running `npm install` results in:

		gyp ERR! build error 
		gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\12.0\bin\msbuild.exe` failed with exit code: 1
		gyp ERR! stack     at ChildProcess.onExit (C:\Program Files (x86)\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:267:23)
		gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
		gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:807:12)
		gyp ERR! System Windows_NT 6.2.9200
		gyp ERR! command "node" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
		gyp ERR! cwd C:\Users\live_000\Documents\Code\node-pathwatcher
		gyp ERR! node -v v0.10.28
		gyp ERR! node-gyp -v v0.13.0
		gyp ERR! not ok 

		npm ERR! pathwatcher@1.2.1 install: `node-gyp rebuild`
		npm ERR! Exit status 1
		npm ERR! 
		npm ERR! Failed at the pathwatcher@1.2.1 install script.
		npm ERR! This is most likely a problem with the pathwatcher package,
		npm ERR! not with npm itself.
		npm ERR! Tell the author that this fails on your system:
		npm ERR!     node-gyp rebuild
		npm ERR! You can get their info via:
		npm ERR!     npm owner ls pathwatcher
		npm ERR! There is likely additional logging output above.
		npm ERR! System Windows_NT 6.2.9200
		npm ERR! command "C:\\Program Files (x86)\\nodejs\\\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
		npm ERR! cwd C:\Users\live_000\Documents\Code\node-pathwatcher
		npm ERR! node -v v0.10.28
		npm ERR! npm -v 1.4.9
		npm ERR! code ELIFECYCLE
		npm ERR! 
		npm ERR! Additional logging details can be found in:
		npm ERR!     C:\Users\live_000\Documents\Code\node-pathwatcher\npm-debug.log
		npm ERR! not ok code 0

First found in atom/atom#2023 but I'm confirming this isn't atom-specific.

**Comment by voltagex** [comment]
I can't re-test this due to system python version >3 - will reopen if necessary.
